name : CI Pipeline - frontend

on:
  push:
    branches:
      - main

jobs:
  # deploy-backend:
  #   name: Deploy Backend Infra
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-west-2

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: 1.5.5

  #     - name: Terraform Init
  #       working-directory: ./backend
  #       run: terraform init

  #     - name: Terraform Validate
  #       working-directory: ./backend
  #       run: terraform validate

  #     - name: Terraform Plan
  #       working-directory: ./backend
  #       run: terraform plan

  #     - name: Terraform Apply
  #       working-directory: ./backend
  #       run: terraform apply -auto-approve
  deploy-frontend:
    name: Deploy Frontend Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'frontend'